name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  POSTGRES_DB: "appdb" 
  POSTGRES_USER: "app_user"
  # POSTGRES_PASSWORD: ${{ secrets.POSTGRESPASS }} 
  POSTGRES_PASSWORD: "app_password"
  POSTGRES_HOST: "10.254.94.29"

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: "windblow"
        password: ${{ secrets.DOCKERHUBPASS }}
    - name: "Build docker container"
      run: |
        docker build . -t windblow/django_example:$GITHUB_SHA 
        docker push windblow/django_example:$GITHUB_SHA 
    - name: "Execute tests in container"
      run: |
        docker run windblow/django_example:$GITHUB_SHA python manage.py test
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: azure/setup-helm@v3
    # - name: 'Deploy'
    #   uses: 'deliverybot/helm@v1'
    #   with:
    #     release: 'django'
    #     namespace: 'default'
    #     chart: 'django-chart'
    #     # token: '${{ github.token }}'
    #     #values: |
    #     #  name: foobar
    #     value-files: >-
    #       [
    #         "values.yaml" 
    #       ]
    - name: "Deploy"
      run: |
        echo '${{ secrets.KUBECONFIG }}' > kubeconfig.yml
        helm upgrade --install --force -f ../values.yaml django django-chart
      env:
        KUBECONFIG: kubeconfig.yml
    # - name: Deploy to stage
    #   run: |
    #     source .github/prod_env
    #     echo "POSTGRES_DB=$POSTGRES_DB" >> .env
    #     echo "POSTGRES_USER=$POSTGRES_USER" >> .env
    #     echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
    #     echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
    #     docker-compose build
    #     docker-compose up -d
