name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  POSTGRES_DB: "appdb" 
  POSTGRES_USER: "app_user"
  # POSTGRES_PASSWORD: ${{ secrets.POSTGRESPASS }} 
  POSTGRES_PASSWORD: "app_password"
  POSTGRES_HOST: "10.254.94.29"

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: "windblow"
        password: ${{ secrets.DOCKERHUBPASS }}
    - name: "Build docker container"
      run: |
        docker build . -t windblow/django_example:$GITHUB_SHA 
        docker push windblow/django_example:$GITHUB_SHA 
    - name: "Execute tests in container"
      run: |
        docker run windblow/django_example:$GITHUB_SHA python manage.py test
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: azure/setup-helm@v3
    - name: "Deploy"
      run: |
        source .github/prod_env
        curl -sSL \
         https://hub.mcs.mail.ru/repository/client-keystone-auth/latest/linux/client-install.sh | bash
        echo '${{ secrets.KUBECONFIG }}' > kubeconfig.yml
        source "/home/runner/.bashrc
        helm upgrade --install --atomic --values values.yaml django infrastructure/django-chart \
         --set-string envConfigs.DB_PASSWORD="$POSTGRES_PASSWORD" \
         --set-string envConfigs.DB_HOST="$POSTGRES_HOST" \
         --set image.tag=$GITHUB_SHA
      env:
        KUBECONFIG: kubeconfig.yml
        POSTGRES_PASSWORD: ${{ secrets.POSTGRESPASS }}
